[package]
name = "strom-object-store"
description = "Object store for StromDB"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
bytes = { workspace = true }
crc32c = { workspace = true }
futures = { workspace = true }
object_store = { workspace = true, features = ["aws"] }
thiserror = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt"] }

[lints]
workspace = true
