[project]
name = "stromdb"
revision = "1.0"

[profiles.default]
AWS_ACCESS_KEY_ID = { description = "AWS access key for the S3-compatible object store", required = true }
AWS_SECRET_ACCESS_KEY = { description = "AWS secret key for the S3-compatible object store", required = true }

[profiles.development]
AWS_ACCESS_KEY_ID = { default = "minioadmin" }
AWS_SECRET_ACCESS_KEY = { default = "minioadmin" }
