[package]
name = "stromdb"
description = "StromDB, the embeddable durable streams database"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
object_store = { workspace = true }
strom-common = { path = "../strom-common", version = "0.1.0" }
strom-domain = { path = "../strom-domain", version = "0.1.0" }
strom-object-store = { path = "../strom-object-store", version = "0.1.0" }
strom-storage-domain = { path = "../strom-storage-domain", version = "0.1.0" }
strom-storage-engine = { path = "../strom-storage-engine", version = "0.1.0" }
thiserror = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt"] }

[lints]
workspace = true
