[profile.default]
retries = 0
fail-fast = false
slow-timeout = { period = "20s", terminate-after = 3 }
leak-timeout = "500ms"

[profile.ci]
fail-fast = true
final-status-level = "flaky"

[profile.mutants]
fail-fast = true
slow-timeout = { period = "5s", terminate-after = 1 }
status-level = "fail"
